# Generated by Django 2.2.4 on 2019-11-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=200)),
                ('test_timestamp', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
