
"""
Django settings for virtualcases project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from .settings_local import ADDITIONAL_APPS
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b($s^hct-r852v!+tzry+4r0sl@g9ujb*#*k71fxh2#a7!1!zc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup.apps.CleanupConfig',
    'testapp.apps.TestappConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'virtualcases.middleware.IFrameMiddleware',
]

ROOT_URLCONF = 'virtualcases.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'virtualcases.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'slide_viewer',
        'USER': 'slide_user',
        'PASSWORD': 'Kz9g5?h8',
        'HOST': '127.0.0.1',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
		'OPTIONS': {
            'init_command': 'SET innodb_strict_mode=1',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# or, depending on your configuration:
DEFAULT_DOMAIN = '//{}'.format(ALLOWED_HOSTS[0])


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# MEDIA_ROOT = os.path.join(BASE_DIR, 'static/labels')

# MEDIA_URL = '/media/'

#STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

STATICFILES_DIRS = (
  os.path.join(BASE_DIR, 'static/'),
)

SLIDEFILE_EXTENSIONS = ('.jpg', '.jpeg', '.mrxs', '.tif', '.tiff', '.svs')
DEEPZOOM_FORMAT = "jpeg"
DEEPZOOM_OVERLAP = 1
DEEPZOOM_TILE_SIZE = 256
HISTOSLIDE_SLIDEROOT = BASE_DIR

INSTALLED_APPS += ADDITIONAL_APPS
# try:
#     from .settings_local import *
# except ImportError:
#     pass

# CSRF Settings
X_FRAME_OPTIONS = 'ALLOW-FROM virtualacp.com, ftmsk.uralensiswebapp.co.uk mskcc.uralensisdigital.co.uk mskcc.uralensiswebapp.co.uk demo.uralensiswebapp.co.uk'
CSRF_TRUSTED_ORIGINS = ['virtualacp.com', 'ftmsk.uralensiswebapp.co.uk', 'mskcc.uralesnsisdigital.co.uk', 'mskcc.uralensisdigital.co.uk/development', 'mskcc.uralensiswebapp.co.uk', 'demo.uralensiswebapp.co.uk']
CSRF_COOKIE_SAMESITE = None
