# Generated by Django 3.0.8 on 2021-01-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frcpathp2surgicalcourse', '0003_auto_20210117_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='frcpathp2surgicalcourse',
            name='GroupName',
            field=models.CharField(default='Group'),
        ),
    ]
