# Generated by Django 3.0.8 on 2021-01-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frcpathp2surgicalcourse', '0004_frcpathp2surgicalcourse_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frcpathp2surgicalcourse',
            name='GroupName',
            field=models.CharField(default='Group', max_length=100),
        ),
    ]
