# Generated by Django 3.0.8 on 2021-01-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frcpathp2surgicalcourse', '0005_auto_20210117_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frcpathp2surgicalcourse',
            name='GroupName',
            field=models.CharField(default='FRCPath', max_length=100),
        ),
    ]
