# Generated by Django 3.0.8 on 2021-01-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frcpathp2surgicalcourse', '0006_auto_20210117_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frcpathp2surgicalcourse',
            name='GroupName',
            field=models.CharField(default='FRCPath Default Group', max_length=100),
        ),
    ]
