# Generated by Django 3.0.8 on 2021-01-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frcpathp2surgicalcourse', '0008_remove_frcpathp2surgicalcourse_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='frcpathp2surgicalcourse',
            name='GroupName',
            field=models.CharField(default='FRCPath Default Group', max_length=100),
        ),
    ]
