# Generated by Django 3.0.8 on 2021-01-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frcpathp2surgicalcourse', '0011_frcpathp2surgicalcourse_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='frcpathp2surgicalcourse',
            name='Annotations',
            field=models.BooleanField(default=False),
        ),
    ]
