# Generated by Django 3.0 on 2019-12-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histoslide', '0003_slide_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='UrlPath',
            field=models.FileField(upload_to='uploads/cases/'),
        ),
    ]
