# Generated by Django 3.0 on 2019-12-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histoslide', '0004_auto_20191224_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='UrlPath',
            field=models.FileField(upload_to='media/uploads/cases/'),
        ),
    ]
