# Generated by Django 2.2 on 2020-06-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Group',
            field=models.IntegerField(default=0),
        ),
    ]
