# Generated by Django 3.0.8 on 2021-01-07 16:23

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='LabelUrlPath',
            field=models.ImageField(default='/mnt/d/projects/slide_app/static/labels/placeholder.png', upload_to=patient.models.UploadToPathAndRename('/mnt/d/projects/slide_app/static/labels')),
        ),
    ]
