# Generated by Django 2.2.5 on 2020-04-15 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liverpooldermpathcourse2020', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Json', models.TextField()),
                ('AnnotationText', models.TextField()),
                ('Type', models.CharField(max_length=10)),
                ('Slide_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liverpooldermpathcourse2020.Liverpooldermpathcourse2020')),
            ],
        ),
    ]
